# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0002_auto_20180906_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='image_url',
        ),
    ]
