# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0003_auto_20180906_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
