# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0004_property_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='age',
        ),
        migrations.RemoveField(
            model_name='property',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='postadd',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
